"use client";
import {useEffect,useState} from "react";
const business={phones:{primary:"07042208536",secondary:"09013353535"},whatsapp:{primary:"2347042208536",secondary:"2349013353535"}};
const general="Hello Tahir Textile, I'm interested in your premium Ankara fabrics. Please send me your available designs and current prices.";
const bulk="Hello Tahir Textile, I'm interested in purchasing fabrics in bulk. Please send me your available options and current wholesale prices.";
const ask="Hello Tahir Textile, I'm interested in this Ankara design. Please let me know if it is currently available and the price.";
const wa=(phone=business.whatsapp.primary,message=general)=>`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
const nav=[["Home","/"],["Collections","/collections"],["About","/about"],["How to Order","/how-to-order"],["Contact","/contact"]] as const;
function Header(){const[o,setO]=useState(false);const[c,setC]=useState(false);useEffect(()=>{const s=()=>setC(scrollY>20),e=(x:KeyboardEvent)=>x.key==="Escape"&&setO(false);addEventListener("scroll",s);addEventListener("keydown",e);return()=>{removeEventListener("scroll",s);removeEventListener("keydown",e)}},[]);useEffect(()=>{document.body.style.overflow=o?"hidden":"";return()=>{document.body.style.overflow=""}},[o]);return <><header className={`header ${c?"compact":""}`}><a href="/" className="brand">TAHIR <i>TEXTILE</i></a><nav className="desktop-nav">{nav.map(([n,h])=><a key={h} href={h}>{n}</a>)}<a className="nav-cta" target="_blank" rel="noreferrer" href={wa()}>WhatsApp Us ↗</a></nav><button className="menu-button" aria-label="Open menu" aria-expanded={o} onClick={()=>setO(true)}><b/><b/></button></header>{o&&<div className="menu-layer" onClick={()=>setO(false)}><aside className="mobile-menu" onClick={e=>e.stopPropagation()}><div className="menu-top"><span className="brand">TAHIR <i>TEXTILE</i></span><button aria-label="Close menu" onClick={()=>setO(false)}>×</button></div><nav>{nav.map(([n,h])=><a key={h} href={h} onClick={()=>setO(false)}>{n}<span>↗</span></a>)}<a className="button gold" target="_blank" rel="noreferrer" href={wa()}>WhatsApp Tahir Textile</a></nav></aside></div>}</>}
function Footer(){return <footer><div className="footer-main"><div><p className="eyebrow">TAHIR TEXTILE</p><h2>Premium Ankara<br/>& Luxury Fabrics.</h2></div><div><p className="footer-label">Explore</p>{nav.map(([n,h])=><a key={h} href={h}>{n}</a>)}</div><div><p className="footer-label">Talk to Tahir</p><a href="tel:07042208536">07042208536</a><a href="tel:09013353535">09013353535</a><a className="footer-wa" target="_blank" rel="noreferrer" href={wa()}>WhatsApp Tahir Textile ↗</a></div></div><div className="footer-bottom"><span>Premium Ankara for classy and serious buyers.</span><span>© {new Date().getFullYear()} Tahir Textile</span></div></footer>}
const names=["Indigo Geometry","Terracotta Rhythm","Gold Linework","Night Garden","Sunlit Mosaic","Royal Current"];
function Lookbook({limit=false}:{limit?:boolean}){return <div className="lookbook-grid">{(limit?names.slice(0,3):names).map((n,i)=><article className={`fabric-card card-${i}`} key={n}><div className="fabric-image" role="img" aria-label={`Editorial placeholder image: ${n} premium Ankara fabric`}/><div className="fabric-copy"><p>{i<3?"Premium Ankara":"Luxury Fabrics"}</p><h3>{n}</h3><span>Price on request</span><a target="_blank" rel="noreferrer" href={wa(undefined,`${ask} Design: ${n}.`)}>Ask about this fabric <b>↗</b></a></div></article>)}</div>}
function Signature(){return <section className="signature"><p className="eyebrow">Tahir Textile</p><h2>PREMIUM ANKARA FOR<br/>CLASSY & SERIOUS<br/><em>BUYERS ONLY.</em></h2><p>If you know what you want, let&apos;s find the fabric that fits it.</p><a className="text-link" href="/collections">View current fabrics <span>↗</span></a></section>}
function Home(){return <><section className="hero"><div className="hero-image" role="img" aria-label="Editorial still life of premium indigo, terracotta and gold Ankara fabrics"/><div className="hero-content"><p className="eyebrow">Kano, Nigeria · Fabric with presence</p><h1>Premium Ankara<br/>for <em>classy</em> & serious<br/>buyers.</h1><p className="intro">Discover premium Ankara and luxury fabrics selected for customers who want distinctive prints, refined style and quality they can see.</p><div className="actions"><a className="button gold" href="/collections">Explore collections</a><a className="text-link light" target="_blank" rel="noreferrer" href={wa()}>WhatsApp Tahir Textile ↗</a></div></div></section><section className="statement"><div><p className="eyebrow">01 — The Tahir standard</p><h2>For those who<br/><em>know</em> good fabric.</h2></div><div><p>Tahir Textile brings premium Ankara and luxury fabric selections to customers who want more than ordinary prints.</p><div className="pillars"><b>Premium Ankara <span>Bold African prints with visual character.</span></b><b>Luxury Fabrics <span>Elevated choices for a distinctive look.</span></b><b>Serious Service <span>Direct conversation for every enquiry.</span></b></div></div></section><section className="featured"><div className="section-head"><div><p className="eyebrow">The collection</p><h2>Fabric worth<br/><em>looking twice</em> at.</h2></div><a className="text-link" href="/collections">View all fabrics ↗</a></div><Lookbook limit/></section><Signature/><section className="wholesale"><div className="wholesale-art"/><div><p className="eyebrow">For serious buyers</p><h2>Buying more<br/>than <em>one?</em></h2><p>Enquire directly about bulk fabric requirements, available designs and current pricing.</p><a className="button dark" target="_blank" rel="noreferrer" href={wa(undefined,bulk)}>Enquire on WhatsApp</a></div></section><section className="social"><p className="eyebrow">See what&apos;s next</p><h2>Follow the latest fabrics.</h2><p>Discover new Ankara designs, fabric drops and visual updates across Tahir Textile&apos;s social channels.</p><div><span>Instagram — account to be confirmed</span><span>Facebook — account to be confirmed</span></div></section></>}
function Collections(){return <><section className="page-hero"><p className="eyebrow">The fabric edit · 01</p><h1>Find the print<br/>that <em>speaks.</em></h1><p>A considered textile lookbook. Ask Tahir Textile directly for availability and current price.</p></section><section className="catalogue"><div className="catalogue-note"><span>All designs</span><span>Price on request · Availability confirmed on WhatsApp</span></div><Lookbook/></section><Signature/></>}
function About(){return <><section className="page-hero"><p className="eyebrow">Tahir Textile · Kano, Nigeria</p><h1>Fabric that makes<br/>an <em>entrance.</em></h1><p>Tahir Textile is a fabric-focused Nigerian brand serving customers looking for premium Ankara and luxury textile selections.</p></section><section className="about-grid"><div className="about-image"/><div><p>Our collections are built around bold African prints, refined fabric choices and designs for customers who take their style seriously.</p>{[["Quality","Selections made for customers who appreciate the visual difference."],["Distinctive Designs","Prints with a point of view, made to be noticed."],["Customer-Focused Service","Direct communication about designs, availability and price."]].map(([a,b])=><div className="belief" key={a}><b>{a}</b><span>{b}</span></div>)}</div></section><Signature/></>}
function Order(){const s=[["01","Browse","Explore the latest available fabrics and collections."],["02","Choose","Find a design that fits your style or occasion."],["03","WhatsApp","Send the design to Tahir Textile through WhatsApp."],["04","Confirm","Confirm current availability, quantity and price."],["05","Complete your order","Follow arrangements confirmed directly with Tahir Textile."]];return <><section className="page-hero"><p className="eyebrow">Direct · simple · considered</p><h1>From fabric<br/>to <em>favourite.</em></h1><p>The best way to order is a direct conversation. We&apos;ve kept it beautifully simple.</p></section><section className="steps">{s.map(([n,t,d])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></article>)}<a className="button gold" target="_blank" rel="noreferrer" href={wa()}>Start a WhatsApp enquiry</a></section></>}
function Contact(){return <section className="contact-page"><p className="eyebrow">Tahir Textile · Direct enquiries</p><h1>Let&apos;s find<br/>your <em>fabric.</em></h1><p>For current designs, prices, availability and orders, speak directly with Tahir Textile.</p><div className="contact-grid">{[[business.phones.primary,business.whatsapp.primary],[business.phones.secondary,business.whatsapp.secondary]].map(([n,w])=><article key={n}><span>WhatsApp / Call</span><a target="_blank" rel="noreferrer" href={wa(w)}>{n} <b>↗</b></a><a href={`tel:${n}`}>Call {n}</a></article>)}</div></section>}
function Detail(){return <section className="detail"><div className="detail-image"/><div><p className="eyebrow">Premium Ankara</p><h1>Indigo<br/><em>Geometry.</em></h1><p>A bold Ankara print selected for customers looking for a distinctive statement fabric.</p><p className="availability">Availability: <b>Check directly with Tahir Textile</b></p><a className="button gold" target="_blank" rel="noreferrer" href={wa(undefined,`${ask} Design: Premium Ankara — Indigo Geometry.`)}>Ask for price on WhatsApp</a></div></section>}
export function PageShell({page}:{page:string}){const content=page==="home"?<Home/>:page==="collections"?<Collections/>:page==="about"?<About/>:page==="order"?<Order/>:page==="contact"?<Contact/>:<Detail/>;return <><Header/><main>{content}</main><Footer/></>}
